# Generated by Django 4.0.4 on 2022-04-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lastname',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='patronymic',
            new_name='NameDad',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='telnumber',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='Username',
        ),
    ]
